# Generated by Django 4.1.2 on 2022-11-04 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0005_product_author_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pname',
            field=models.CharField(max_length=80, verbose_name='Product Name'),
        ),
    ]
