# Generated by Django 4.1.2 on 2022-11-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0008_product_oprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Oprice',
        ),
        migrations.AddField(
            model_name='product',
            name='originalprice',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
