# Generated by Django 4.1.2 on 2022-11-04 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0009_remove_product_oprice_product_originalprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='originalprice',
            field=models.IntegerField(),
        ),
    ]
