# Generated by Django 4.1.2 on 2022-11-04 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0011_alter_product_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='originalprice',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='qty',
            field=models.IntegerField(),
        ),
    ]
