# Generated by Django 4.1.2 on 2022-11-04 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0015_remove_product_originalprice_product_price1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price1',
        ),
    ]
